<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <packaging>jar</packaging>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <!-- <version>3.5.10</version> -->
    <version>4.0.4</version>
    <relativePath></relativePath>
    <!-- lookup parent from repository -->
  </parent>
  <groupId>com.inlaco</groupId>
  <artifactId>crewmgrservice</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>crewmgrservice</name>
  <description>The backend performs crew supply management functions of inlaco company</description>
  <url></url>
  <licenses>
    <license></license>
  </licenses>
  <developers>
    <developer>
      <id>tung</id>
      <name>Tran Vo Son Tung</name>
      <email>sontungexpt@gmail.com</email>
      <roles>
        <role>backend developer</role>
      </roles>
      <timezone>VietNam/Ho_Chi_Minh</timezone>
    </developer>
  </developers>
  <scm>
    <connection></connection>
    <developerConnection></developerConnection>
    <tag></tag>
    <url></url>
  </scm>
  <properties>
    <java.version>21</java.version>
    <kotlin.version>2.3.20</kotlin.version>
    <therapi.version>0.15.0</therapi.version>
    <jjwt.version>0.13.0</jjwt.version>
    <cloudinary.version>2.3.2</cloudinary.version>
    <jnanoid.version>2.0.0</jnanoid.version>
    <dotenv.version>5.1.0</dotenv.version>
    <slugify.version>3.0.7</slugify.version>
    <icu4j.version>78.3</icu4j.version>
    <springdoc.version>3.0.2</springdoc.version>
    <json-patch.version>1.13</json-patch.version>
    <resend.version>4.13.0</resend.version>
    <springfilter.version>3.2.5</springfilter.version>
    <javaxjson.version>1.1.4</javaxjson.version>
    <org.mapstruct.version>1.7.0.Beta1</org.mapstruct.version>
    <spring-retry.version>2.0.12</spring-retry.version>
    <spring-aop.version>4.0.0-M2</spring-aop.version>
    <flapdoodle-embed-mongo.version>4.24.0</flapdoodle-embed-mongo.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>me.paulschwarz</groupId>
        <artifactId>spring-dotenv-bom</artifactId>
        <version>${dotenv.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>me.paulschwarz</groupId>
      <artifactId>springboot4-dotenv</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-reflect</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-logging</artifactId>
    </dependency>
    <!-- <dependency> -->
    <!--   <groupId>org.eclipse.angus</groupId> -->
    <!--   <artifactId>angus-activation</artifactId> -->
    <!-- </dependency> -->
    <!-- <dependency> -->
    <!--   <groupId>org.eclipse.angus</groupId> -->
    <!--   <artifactId>angus-mail</artifactId> -->
    <!-- </dependency> -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-mail</artifactId>
    </dependency>
    <dependency>
      <groupId>com.resend</groupId>
      <artifactId>resend-java</artifactId>
      <version>${resend.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-websocket</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-devtools</artifactId>
      <scope>runtime</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-mongodb</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <!-- https://mvnrepository.com/artifact/org.mapstruct/mapstruct-processor -->
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct-processor</artifactId>
      <version>${org.mapstruct.version}</version>
    </dependency>
    <dependency>
      <!-- https://mvnrepository.com/artifact/org.mapstruct/mapstruct -->
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct</artifactId>
      <version>${org.mapstruct.version}</version>
    </dependency>
    <!-- test -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-mongodb-test</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- Source: https://mvnrepository.com/artifact/de.flapdoodle.embed/de.flapdoodle.embed.mongo -->
    <dependency>
      <groupId>de.flapdoodle.embed</groupId>
      <artifactId>de.flapdoodle.embed.mongo</artifactId>
      <version>${flapdoodle-embed-mongo.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-test-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-params</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webmvc-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-test</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- Filter JPA entities directly in database queries. The module converts filter expressions to JPA Criteria API specifications. -->
    <!-- <dependency> -->
    <!--   <groupId>com.turkraft.springfilter</groupId> -->
    <!--   <artifactId>jpa</artifactId> -->
    <!--   <version>${springfilter.version}</version> -->
    <!-- </dependency> -->
    <!-- Filter in-memory collections using Java Predicates. Works with any POJO, no database required. -->
    <!--     <dependency> -->
    <!--   <groupId>com.turkraft.springfilter</groupId> -->
    <!--   <artifactId>predicate</artifactId> -->
    <!--       <version>${springfilter.version}</version> -->
    <!-- </dependency> -->
    <!-- Filter MongoDB documents using Spring Data MongoDB queries. -->
    <!-- <dependency> -->
    <!--   <groupId>com.turkraft.springfilter</groupId> -->
    <!--   <artifactId>mongo</artifactId> -->
    <!--   <version>${springfilter.version}</version> -->
    <!-- </dependency> -->
    <!-- <dependency> -->
    <!--   <groupId>com.turkraft.springfilter</groupId> -->
    <!--   <artifactId>core</artifactId> -->
    <!--   <version>${springfilter.version}</version> -->
    <!-- </dependency> -->
    <!-- <dependency> -->
    <!--   <groupId>com.turkraft.springfilter</groupId> -->
    <!--   <artifactId>page-sort</artifactId> -->
    <!--   <version>${springfilter.version}</version> -->
    <!-- </dependency> -->
    <!-- <dependency> -->
    <!--   <groupId>com.turkraft.springfilter</groupId> -->
    <!--   <artifactId>openapi</artifactId> -->
    <!--   <version>${springfilter.version}</version> -->
    <!-- </dependency> -->
    <!-- <dependency> -->
    <!--   <groupId>org.springdoc</groupId> -->
    <!--   <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId> -->
    <!--   <version>${springdoc.version}</version> -->
    <!-- </dependency> -->
    <!-- Source: https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-scalar -->
    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-scalar</artifactId>
      <version>${springdoc.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.github.therapi</groupId>
      <artifactId>therapi-runtime-javadoc</artifactId>
      <version>${therapi.version}</version>
    </dependency>
    <dependency>
      <groupId>com.aventrix.jnanoid</groupId>
      <artifactId>jnanoid</artifactId>
      <version>${jnanoid.version}</version>
    </dependency>
    <!-- json patch -->
    <dependency>
      <!-- Source: https://mvnrepository.com/artifact/com.github.java-json-tools/json-patch -->
      <groupId>com.github.java-json-tools</groupId>
      <artifactId>json-patch</artifactId>
      <version>${json-patch.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-jsr353</artifactId>
    </dependency>
    <dependency>
      <groupId>org.glassfish</groupId>
      <artifactId>javax.json</artifactId>
      <version>${javaxjson.version}</version>
      <scope>compile</scope>
    </dependency>
    <!-- json patch -->
    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt-api</artifactId>
      <version>${jjwt.version}</version>
    </dependency>
    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt-jackson</artifactId>
      <!-- or jjwt-gson if Gson is preferred -->
      <version>${jjwt.version}</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt-impl</artifactId>
      <version>${jjwt.version}</version>
      <scope>runtime</scope>
    </dependency>
    <!-- Source: https://mvnrepository.com/artifact/org.springframework.retry/spring-retry -->
    <dependency>
      <groupId>org.springframework.retry</groupId>
      <artifactId>spring-retry</artifactId>
      <version>${spring-retry.version}</version>
      <scope>compile</scope>
    </dependency>
    <!-- Source: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-aop -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-aop</artifactId>
      <version>${spring-aop.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-cache</artifactId>
    </dependency>
    <dependency>
      <groupId>com.github.ben-manes.caffeine</groupId>
      <artifactId>caffeine</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-redis</artifactId>
    </dependency>
    <dependency>
      <groupId>com.github.slugify</groupId>
      <artifactId>slugify</artifactId>
      <version>${slugify.version}</version>
    </dependency>
    <dependency>
      <groupId>com.ibm.icu</groupId>
      <artifactId>icu4j</artifactId>
      <version>${icu4j.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.cloudinary/cloudinary-http5 -->
    <dependency>
      <groupId>com.cloudinary</groupId>
      <artifactId>cloudinary-http5</artifactId>
      <version>${cloudinary.version}</version>
    </dependency>
    <dependency>
      <groupId>com.cloudinary</groupId>
      <artifactId>cloudinary-taglib</artifactId>
      <version>${cloudinary.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-thymeleaf</artifactId>
    </dependency>
  </dependencies>
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.jetbrains.kotlin</groupId>
          <artifactId>kotlin-maven-plugin</artifactId>
          <version>${kotlin.version}</version>
          <extensions>true</extensions>
          <configuration>
            <!-- Allow Kotlin reading Java folder -->
            <sourceDirs>
              <sourceDir>src/main/java</sourceDir>
            </sourceDirs>
            <testSourceDirs>
              <testSourceDir>src/test/java</testSourceDir>
            </testSourceDirs>
            <args>
              <arg>-Xjsr305=strict</arg>
              <arg>-Xannotation-default-target=param-property</arg>
            </args>
            <compilerPlugins>
              <plugin>spring</plugin>
            </compilerPlugins>
            <!-- Fix annotation processor (MapStruct, Lombok, Therapi) -->
            <annotationProcessorPaths>
              <path>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
              </path>
              <path>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${org.mapstruct.version}</version>
              </path>
              <path>
                <groupId>com.github.therapi</groupId>
                <artifactId>therapi-runtime-javadoc-scribe</artifactId>
                <version>${therapi.version}</version>
              </path>
            </annotationProcessorPaths>
          </configuration>
          <dependencies>
            <dependency>
              <groupId>org.jetbrains.kotlin</groupId>
              <artifactId>kotlin-maven-allopen</artifactId>
              <version>${kotlin.version}</version>
            </dependency>
          </dependencies>
          <!-- Ensure kotlin compile before java -->
          <executions>
            <execution>
              <id>kotlin-compile</id>
              <phase>compile</phase>
              <goals>
                <goal>compile</goal>
              </goals>
            </execution>
            <execution>
              <id>kotlin-test-compile</id>
              <phase>test-compile</phase>
              <goals>
                <goal>test-compile</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <!-- Activate Kotlin Maven plugin for main and test sources -->
        <!-- <plugin> -->
        <!--   <groupId>org.jetbrains.kotlin</groupId> -->
        <!--   <artifactId>kotlin-maven-plugin</artifactId> -->
        <!--   <version>${kotlin.version}</version> -->
        <!-- lets Maven integrate the Kotlin plugin into the build lifecycle. -->
        <!--   <extensions>true</extensions> -->
        <!--   <configuration> -->
        <!--     <annotationProcessorPaths> -->
        <!--       <path> -->
        <!--         <groupId>org.projectlombok</groupId> -->
        <!--         <artifactId>lombok</artifactId> -->
        <!--       </path> -->
        <!--       <path> -->
        <!--         <groupId>com.github.therapi</groupId> -->
        <!--         <artifactId>therapi-runtime-javadoc-scribe</artifactId> -->
        <!--         <version>${therapi.version}</version> -->
        <!--       </path> -->
        <!--     </annotationProcessorPaths> -->
        <!--     <args> -->
        <!--       <arg>-Xjsr305=strict</arg> -->
        <!--       <arg>-Xannotation-default-target=param-property</arg> -->
        <!--     </args> -->
        <!--     <compilerPlugins> -->
        <!--       <plugin>spring</plugin> -->
        <!--     </compilerPlugins> -->
        <!--   </configuration> -->
        <!--   <dependencies> -->
        <!--     <dependency> -->
        <!--       <groupId>org.jetbrains.kotlin</groupId> -->
        <!--       <artifactId>kotlin-maven-allopen</artifactId> -->
        <!--       <version>${kotlin.version}</version> -->
        <!--     </dependency> -->
        <!--   </dependencies> -->
        <!-- Custom execution phases allow the Kotlin plugin to compile Kotlin first, then Java. -->
        <!--   <executions> -->
        <!--     <execution> -->
        <!--       <id>default-compile</id> -->
        <!--       <phase>compile</phase> -->
        <!--       <configuration> -->
        <!--         <sourceDirs> -->
        <!--           <sourceDir>src/main/java</sourceDir> -->
        <!--         </sourceDirs> -->
        <!--       </configuration> -->
        <!--     </execution> -->
        <!--     <execution> -->
        <!--       <id>default-test-compile</id> -->
        <!--       <phase>test-compile</phase> -->
        <!--       <configuration> -->
        <!--         <sourceDirs> -->
        <!--           <sourceDir>src/test/java</sourceDir> -->
        <!--         </sourceDirs> -->
        <!--       </configuration> -->
        <!--     </execution> -->
        <!--   </executions> -->
        <!-- </plugin> -->
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
