debug: false

caching:
  spring:
    userListTTL: 60000

vonage:
  api-key: ${VONAGE_API_KEY}
  api-secret: ${VONAGE_API_SECRET}
  sender: ${VONAGE_SENDER:Inlaco}

httpsms:
  api-key: ${HTTPSMS_API_KEY}
  sender: "+84392211343"
  api-secret: ${HTTPSMS_SECRET_KEY}

jwt:
  # inlaco.JWT-secret-key
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: 300000 # 5 mins
  refresh-token-expiration: 2592000000 # 30 days

spring:
  application:
    name: "crewmgrservice"
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    transport:
      protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
    # cache-names:
    #   - rate-limit-buckets
    #   - rate-limit-filter
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ${MONGO_DATABASE}
      # uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_DATABASE}.e2nsr.mongodb.net/?retryWrites=true&w=majority&appName=${MONGO_DATABASE}
      autoIndexCreation: true
    # redis:
    #   host: ${REDIS_HOST}
    #   port: ${REDIS_PORT}
    # password: ${REDIS_PASSWORD:IxXNUvoIE4ZywfZ8PMZ0nmVxVzKwUeC3}

inlaco:
