package com.inlaco.crewmgrservice.feature.upload.domain.enums;

public enum AssetType {
  DEFAULT,
  COURSE_WALLPAPER,
  TRAINING_PROVIDER_LOGO,
  RESUME,
  CONTRACT_TEMPLATE,
  CREW_RENTAL_REQUEST_DETAIL_FILE,
  CONTRACT_FILE,
  SHIP_IMAGE,
  POST_IMAGE,
  POST_ATTACHMENT,

  CREW_PROFILE,
  CITIZEN_IDENTITY_CARD,
  SOCIAL_INSURANCE,
  ACCIDENT_INSURANCE,
}
